/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog6112;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;

/**
 *
 * @author st10083262
 */
public class Commision extends javax.swing.JFrame {

    private static final String[] locations = {"Cape Town", "Durban", "Pretoria"};

    /**
     * Creates new form Commision
     */
    public Commision() {
        initComponents();

        this.AgentLocationComboBox.removeAllItems();
        this.EstateAgentNameTxtField.setText("");
        this.PropertyPriceTxtField.setText("");
        this.CommissionPercentageTxtField.setText("");

        for (int i = 0; i < locations.length; i++) {
            this.AgentLocationComboBox.addItem(locations[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AgentLocationComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EstateAgentNameTxtField = new javax.swing.JTextField();
        PropertyPriceTxtField = new javax.swing.JTextField();
        CommissionPercentageTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        EstateAgentReportTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ProcessReportMenuItem = new javax.swing.JMenuItem();
        ClearReportMenuItem = new javax.swing.JMenuItem();
        SaveReportMenuItem = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("AGENT LOCATION:");

        AgentLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("ESTATE AGENT NAME:");

        jLabel4.setText("PROPERTY PRICE:");

        jLabel5.setText("COMMISSION PERCENTAGE:");

        jLabel6.setText("ESTATE AGENT REPORT:");

        EstateAgentNameTxtField.setText("jTextField1");
        EstateAgentNameTxtField.setPreferredSize(new java.awt.Dimension(164, 25));

        PropertyPriceTxtField.setText("jTextField2");
        PropertyPriceTxtField.setPreferredSize(new java.awt.Dimension(164, 25));

        CommissionPercentageTxtField.setText("jTextField3");
        CommissionPercentageTxtField.setPreferredSize(new java.awt.Dimension(164, 25));

        EstateAgentReportTextArea.setEditable(false);
        EstateAgentReportTextArea.setColumns(20);
        EstateAgentReportTextArea.setRows(5);
        jScrollPane1.setViewportView(EstateAgentReportTextArea);

        FileMenu.setText("File");

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        jMenu2.setText("Tools");

        ProcessReportMenuItem.setText("Process Report");
        ProcessReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ProcessReportMenuItem);

        ClearReportMenuItem.setText("Clear");
        ClearReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ClearReportMenuItem);

        SaveReportMenuItem.setText("Save Report");
        SaveReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveReportMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(SaveReportMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgentLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EstateAgentNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PropertyPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(CommissionPercentageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgentLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(EstateAgentNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(PropertyPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CommissionPercentageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReportMenuItemActionPerformed
        try {
            FileWriter fw = new FileWriter("report.txt");
            var pw = new PrintWriter(fw);

            String location = (String) AgentLocationComboBox.getSelectedItem();
            String name = EstateAgentNameTxtField.getText();
            String Price = PropertyPriceTxtField.getText();
            String CommissionPercent = CommissionPercentageTxtField.getText();

            Data data = new Data(location, name, Price, CommissionPercent);

            EstateAgent agent = new EstateAgent();

            if (agent.ValidateData(data)) {
                String message = "";
                pw.append("ESTATE AGENT REPORT\n");
                pw.append("*********************************************\n");
                pw.append("AGENT LOCATION: " + location + "\n");
                pw.append("AGENT NAME: " + name + "\n");
                pw.append("PROPERTY PRICE: R " + Price + "\n");
                pw.append("COMMISSION PERCENTAGE: " + CommissionPercent + "%\n");
                pw.append("CALCULATED COMMISSION: R " + agent.CalculateCommission(Price, CommissionPercent) + "\n");
                pw.append("*********************************************");

            }

            pw.close();
            fw.close();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_SaveReportMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // Exit Program
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void ProcessReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessReportMenuItemActionPerformed

        String location = (String) AgentLocationComboBox.getSelectedItem();
        String name = EstateAgentNameTxtField.getText();
        String Price = PropertyPriceTxtField.getText();
        String CommissionPercent = CommissionPercentageTxtField.getText();

        Data data = new Data(location, name, Price, CommissionPercent);

        EstateAgent agent = new EstateAgent();

        if (agent.ValidateData(data)) {
            String message = "";
            message += "ESTATE AGENT REPORT\n";
            message += "*********************************************\n";
            message += "AGENT LOCATION: " + location + "\n";
            message += "AGENT NAME: " + name + "\n";
            message += "PROPERTY PRICE: R " + Price + "\n";
            message += "COMMISSION PERCENTAGE: " + CommissionPercent + "%\n";
            message += "CALCULATED COMMISSION: R " + agent.CalculateCommission(Price, CommissionPercent) + "\n";
            message += "*********************************************";

            EstateAgentReportTextArea.setText(message);
        }

    }//GEN-LAST:event_ProcessReportMenuItemActionPerformed

    private void ClearReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearReportMenuItemActionPerformed
        this.EstateAgentNameTxtField.setText("");
        this.PropertyPriceTxtField.setText("");
        this.CommissionPercentageTxtField.setText("");
        this.EstateAgentReportTextArea.setText("");
    }//GEN-LAST:event_ClearReportMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgentLocationComboBox;
    private javax.swing.JMenuItem ClearReportMenuItem;
    private javax.swing.JTextField CommissionPercentageTxtField;
    private javax.swing.JTextField EstateAgentNameTxtField;
    private javax.swing.JTextArea EstateAgentReportTextArea;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem ProcessReportMenuItem;
    private javax.swing.JTextField PropertyPriceTxtField;
    private javax.swing.JMenuItem SaveReportMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
